name: appinio_social_share
description: Supports sharing text, images, files and text with image to social media (Facebook, Instagram, Instagram Story, Messenger, Telegram, WhatsApp, Twitter, Tiktok, SMS, System, etc.).
version: 0.2.5
homepage: https://github.com/appinioGmbH/flutter_packages
repository: https://github.com/appinioGmbH/flutter_packages/tree/main/packages/appinio_social_share

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.2"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface:

dev_dependencies:
  flutter_test:
    sdk: flutter
#  flutter_lints:

flutter:
  plugin:
    platforms:
      android:
        package: com.appinio.socialshare.appinio_social_share
        pluginClass: AppinioSocialSharePlugin
      ios:
        pluginClass: AppinioSocialSharePlugin
